Update shared.lua
sachera/factorio-deadlocks-stacking-for-pyanodon pull request #2
Opened 2018-12-22 17:47 UTC by RubberDuck1977

i hope this is the correct way now
added soil,glass,sand,pure sand and capacitor 1

2018-12-22 18:04 UTC, sachera commented
It is.

Could you please include the changes regarding the info.json and shared.jua into a single pull request. Pull request should contain all changes needed to sole a certain issue or to add a feature. Since you add an item in this pull request from the mod pyrawores the change in info.json to include this mod as an optional dependency should therefore be part of the same (this) pull request.

2018-12-22 18:26 UTC, RubberDuck1977 commented
o and how do i do that?
im a noob so forgive me

2018-12-22 18:42 UTC, RubberDuck1977 commented
> o and how do i do that?
> im a noob so forgive me
i did spot a mistake in the coding already
also i could not get capacitor 1 stacked

2018-12-22 20:22 UTC, sachera commented
I would cherry pick the commit from the other branch. but it is probably easier for the beginning to just reapply the same changes on the branch this pull request was made from (https://github.com/RubberDuck1977/factorio-deadlocks-stacking-for-pyanodon/tree/patch-2). The pull request should be updated automatically as soon as you commit and push these changes to the patch-2 branch.

2018-12-23 00:15 UTC, sachera requested changes
Change the marked lines and add the changes to the info.json as requested earlier. As soon as thats done i will merge the pull-request and release the new Version.

2018-12-23 00:15 UTC, sachera commented on src/migrations/shared.lua
> +    { item = "capacitor-1", icon = nil, stage = 1 }
its called "capacitor1" without the "-"
```suggestion
     { item = "capacitor1", icon = nil, stage = 1 }
```

2018-12-23 00:15 UTC, sachera commented on src/migrations/shared.lua
> +    { item = "glass", icon = nil, stage = 1 }
Seems like you forgot to close one brace pair

```suggestion
    { item = "glass", icon = nil, stage = 1 }
   }
```

2018-12-27 06:22 UTC, closed without merging

2018-12-27 06:23 UTC, RubberDuck1977 commented
im currently changing the code on your end now